package by.epam.nb.controller;

public enum CommandName {
	CREATE_NOTEBOOK_COMMAND, ADD_NOTE_COMMAND, FIND_BY_NOTE_TEXT_COMMAND, FIND_BY_NOTE_DATE_COMMAND, SAVE_NOTEBOOK_COMMAND, LOAD_NOTEBOOK_COMMAND
}
